<?php
require_once __DIR__ . '/../../../config.php';
require_once __DIR__ . '/../../../config/database.php';

$continent_folder = basename(dirname(dirname(__FILE__)));
$stmt = $pdo->prepare("SELECT * FROM regions WHERE slug = ? AND status = 'active'");
$stmt->execute([$continent_folder]);
$region = $stmt->fetch();

if (!$region) {
    header('Location: ../index.php');
    exit;
}

$page_title = "Travel Calendar - " . $region['name'] . " - iForYoungTours";

// Get tours for this continent
$stmt = $pdo->prepare("
    SELECT t.*, c.name as country_name, c.slug as country_slug
    FROM tours t
    JOIN countries c ON t.country_id = c.id
    WHERE c.region_id = ? AND t.status = 'active'
    ORDER BY t.created_at DESC
");
$stmt->execute([$region['id']]);
$tours = $stmt->fetchAll();

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $page_title; ?></title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>

<!-- Hero Section -->
<section class="relative bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white py-20">
    <div class="container mx-auto px-4 relative z-10">
        <div class="max-w-4xl mx-auto text-center">
            <h1 class="text-4xl md:text-5xl font-bold mb-4">
                Travel Calendar - <?php echo htmlspecialchars($region['name']); ?>
            </h1>
            <p class="text-xl text-slate-300 mb-8">
                Plan your perfect trip with our scheduled departures
            </p>
        </div>
    </div>
</section>

<!-- Calendar Section -->
<section class="py-16 bg-slate-50">
    <div class="container mx-auto px-4">
        <!-- Month Navigation -->
        <div class="bg-white rounded-xl shadow-lg p-6 mb-8">
            <div class="flex items-center justify-between mb-6">
                <h2 class="text-2xl font-bold text-slate-800">Upcoming Departures</h2>
                <div class="flex gap-2">
                    <button onclick="previousMonth()" class="p-2 bg-gray-100 rounded-lg hover:bg-gray-200">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <button onclick="nextMonth()" class="p-2 bg-gray-100 rounded-lg hover:bg-gray-200">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
            </div>
            
            <!-- Calendar Grid -->
            <div id="calendar-container" class="grid grid-cols-7 gap-2">
                <!-- Calendar will be generated by JavaScript -->
            </div>
        </div>

        <!-- Scheduled Tours List -->
        <div class="space-y-6">
            <h3 class="text-2xl font-bold text-slate-800">Scheduled Tours</h3>
            
            <?php if (empty($tours)): ?>
            <div class="bg-white rounded-xl shadow-lg p-8 text-center">
                <i class="fas fa-calendar-alt text-6xl text-slate-300 mb-4"></i>
                <p class="text-xl text-slate-600">No scheduled tours available yet.</p>
                <p class="text-slate-500 mt-2">Check back soon for upcoming departures!</p>
            </div>
            <?php else: ?>
            
            <?php foreach ($tours as $tour): ?>
            <div class="bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow">
                <div class="flex">
                    <div class="w-32 h-24 flex-shrink-0">
                        <img src="<?php echo BASE_URL; ?>/uploads/tours/<?php echo $tour['cover_image'] ?: $tour['image_url']; ?>" onerror="this.src='<?php echo BASE_URL; ?>/assets/images/default-tour.jpg';"
                             alt="<?php echo htmlspecialchars($tour['name']); ?>"
                             class="w-full h-full object-cover">
                    </div>
                    
                    <div class="flex-1 p-4">
                        <div class="flex items-center justify-between mb-2">
                            <div class="flex items-center gap-2">
                                <span class="text-sm text-yellow-600 font-semibold"><?php echo htmlspecialchars($tour['country_name']); ?></span>
                                <span class="text-sm text-gray-400">•</span>
                                <span class="text-sm text-gray-500"><?php echo $tour['duration_days']; ?> days</span>
                            </div>
                            <div class="text-right">
                                <div class="text-lg font-bold text-yellow-600">$<?php echo number_format($tour['price'], 0); ?></div>
                                <div class="text-xs text-gray-500">per person</div>
                            </div>
                        </div>
                        
                        <h4 class="text-lg font-bold text-gray-900 mb-2"><?php echo htmlspecialchars($tour['name']); ?></h4>
                        <p class="text-gray-600 text-sm mb-3"><?php echo htmlspecialchars(substr($tour['description'] ?? 'Discover amazing experiences', 0, 100)) . '...'; ?></p>
                        
                        <div class="flex items-center justify-between">
                            <div class="flex items-center gap-4">
                                <span class="text-xs text-green-600 bg-green-100 px-2 py-1 rounded-full">Available</span>
                                <span class="text-xs text-gray-500">Book anytime</span>
                            </div>
                            <a href="<?php echo $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST']; ?>/pages/tour-detail.php?id=<?php echo $tour['id']; ?>" class="bg-gradient-to-r from-yellow-500 to-orange-500 text-white px-4 py-2 rounded-lg text-sm font-semibold hover:shadow-lg transition-all">
                                View Details
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</section>

<?php include 'enhanced-booking-modal.php'; ?>

<script>
let currentMonth = new Date().getMonth();
let currentYear = new Date().getFullYear();

function generateCalendar(month, year) {
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const monthNames = ["January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"];
    
    let calendarHTML = `
        <div class="col-span-7 text-center font-bold text-lg mb-4">
            ${monthNames[month]} ${year}
        </div>
        <div class="text-center font-semibold text-slate-600">Sun</div>
        <div class="text-center font-semibold text-slate-600">Mon</div>
        <div class="text-center font-semibold text-slate-600">Tue</div>
        <div class="text-center font-semibold text-slate-600">Wed</div>
        <div class="text-center font-semibold text-slate-600">Thu</div>
        <div class="text-center font-semibold text-slate-600">Fri</div>
        <div class="text-center font-semibold text-slate-600">Sat</div>
    `;
    
    // Empty cells for days before month starts
    for (let i = 0; i < firstDay; i++) {
        calendarHTML += '<div class="p-2"></div>';
    }
    
    // Days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const isToday = new Date().toDateString() === new Date(year, month, day).toDateString();
        const todayClass = isToday ? 'bg-gold text-white' : 'hover:bg-slate-100';
        
        calendarHTML += `
            <div class="p-2 text-center cursor-pointer rounded ${todayClass}">
                ${day}
            </div>
        `;
    }
    
    document.getElementById('calendar-container').innerHTML = calendarHTML;
}

function previousMonth() {
    currentMonth--;
    if (currentMonth < 0) {
        currentMonth = 11;
        currentYear--;
    }
    generateCalendar(currentMonth, currentYear);
}

function nextMonth() {
    currentMonth++;
    if (currentMonth > 11) {
        currentMonth = 0;
        currentYear++;
    }
    generateCalendar(currentMonth, currentYear);
}

// Initialize calendar
generateCalendar(currentMonth, currentYear);
</script>

<script src="<?= BASE_URL ?>/assets/js/booking.js"></script>

<?php include '../../../includes/footer.php'; ?>
</body>
</html>